### PR TITLE
Rename view-date.md to view-data.md

### PR DESCRIPTION
**Pull request by glennon**
Minor title refactor: "view-date.md" should be "view-data.md"

### CODE REVIEW

**Comment by glennon** [comment]
II have not looked at the Table of Contents code. Presumably, it will need to be updated.

**Review by fountaingeyser — COMMENTED** [review]
Even though I intentionally used the name `view-date.md` in accordance with our naming during development (i.e., date.php for web and DateActivity for Android), I am also fine with changing it to that. Whatever you prefer... 🤷‍♂️

**Comment by EZWrighter** [comment]
I would agree, view-date seems to target the verb-noun correctly.   Not
sure why it would be changed to view-data.

**Comment by taltstidl** [comment]
Per comments I am closing this pull request.

**Pull request closed without merging**
